package com.eli.bettermb.gui;

import javax.swing.*;
import javax.swing.event.*;
import javax.swing.table.*;
import java.awt.*;
import java.awt.event.*;

class QuotaView extends JPanel
{
    JLabel title = new JLabel("Quota");
    JTextField quotaIncreaseInput = new JTextField();
    JTextField quotaDecreaseInput = new JTextField();
    JTextField cobIncreaseInput = new JTextField();
    JTextField cobDecreaseInput = new JTextField();

    JLabel quotaIncreaseLabel = new JLabel("Increase Quota");
    JLabel quotaDecreaseLabel = new JLabel("Decrease Quota");
    JLabel cobIncreaseLabel   = new JLabel("Increase COB"  );
    JLabel cobDecreaseLabel   = new JLabel("Decrease COB"  );

    final JTextField[] textfields = {
        quotaIncreaseInput,
        quotaDecreaseInput,
        cobIncreaseInput,
        cobDecreaseInput
    };

    final JLabel[] labels = {
        quotaIncreaseLabel,
        quotaDecreaseLabel,
        cobIncreaseLabel,
        cobDecreaseLabel
    };

    QuotaView()
    {
        // NOTE: most of this generated by ChatGPT, so I dont really know whats
        // happening here
        setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        setBorder(BorderFactory.createEmptyBorder(15, 20, 15, 20));

        // Top heading
        JLabel title = new JLabel("Manage Quota/COB");
        title.setBorder(BorderFactory.createEmptyBorder(0, 0, 20, 0));

        add(title);

        // Table data
        String[] columns = {"", ""};

        String[][] data = {
                {"Your current quota", "R16800.00"},
                {"Your current COB quota", "R187.01"},
                {"Your available balance", "R3440.67"}
        };


        JTable table = new JTable(data, columns);

        table.setRowHeight(36);
        table.setShowGrid(true);
        table.setGridColor(new Color(220, 220, 220));

        // Remove column headers
        table.setTableHeader(null);

        DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
        leftRenderer.setHorizontalAlignment(SwingConstants.LEFT);

        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.LEFT);


        table.getColumnModel().getColumn(0)
                .setCellRenderer(leftRenderer);

        table.getColumnModel().getColumn(1)
                .setCellRenderer(rightRenderer);

        add(table);


        String[] options = {
                "Increase Quota" ,
                "Decrease Quota",
                "Increase COB",
                "Decrease COB"
        };

        JPanel content = new JPanel();
        GroupLayout layout = new GroupLayout(content);
        content.setLayout(layout);

        layout.setAutoCreateGaps(true);
        layout.setAutoCreateContainerGaps(true);

        final int textFieldColumns = 32;
        for (JTextField input: textfields) input.setColumns(textFieldColumns);

        var horizontalGroup = layout.createSequentialGroup();

        var horizontalParallelGroup1 = layout.createParallelGroup();
        for (JLabel label: labels) horizontalParallelGroup1.addComponent(label);
        horizontalGroup.addGroup(horizontalParallelGroup1);

        var horizontalParallelGroup2 = layout.createParallelGroup();
        for (JTextField input: textfields) horizontalParallelGroup2.addComponent(input);
        horizontalGroup.addGroup(horizontalParallelGroup2);

        layout.setHorizontalGroup(horizontalGroup);

        var verticalGroup = layout.createSequentialGroup();
        for (int i = 0; i < textfields.length; i++)
        {
            verticalGroup.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labels[i])
                    .addComponent(textfields[i]));
        }
        layout.setVerticalGroup(verticalGroup);


        // GridBagConstraints gbc = new GridBagConstraints();
        // // gbc.insets = new Insets(8, 8, 8, 8);
        // gbc.fill = GridBagConstraints.HORIZONTAL;
        //
        // for (int i = 0; i < options.length; i++)
        // {
        //     // JLabel label = new JLabel(options[i]);
        //     // JTextField input = new JTextField();
        //     //
        //     // label.setHorizontalAlignment(SwingConstants.RIGHT);
        //     //
        //     // gbc.gridx = 0;
        //     // gbc.gridy = i;
        //     // gbc.weightx = 0.5;
        //     // panel.add(label, gbc);
        //     //
        //     // gbc.gridx = 1;
        //     // gbc.weightx = 0.5;
        //     // panel.add(input, gbc);
        //     JPanel input = createInputField(new JLabel(options[i]), new JTextField());
        //     add(input);
        // }
        //
        add(content);
    }

    JPanel createInputField(JComponent desc, JComponent field)
    {
        JPanel panel = new JPanel(new BorderLayout());
        panel.add(desc, BorderLayout.WEST);
        panel.add(field, BorderLayout.CENTER);

        Dimension maxSize = new Dimension(Integer.MAX_VALUE, panel.getPreferredSize().height);
        panel.setMaximumSize(maxSize);

        return panel;
    }
}

class QuotaModel
{
}

class QuotaController
{
    QuotaView view = new QuotaView();
}
