package com.eli.bettermb.gui;

import com.eli.bettermb.client.QuotaSummary;

import javax.swing.*;
import javax.swing.border.Border;
import javax.swing.event.*;
import javax.swing.table.*;
import java.awt.*;
import java.awt.event.*;

class SwingExtensions
{
    static void setMaximumSize(JComponent component, int width, int height)
    {
        Dimension size = new Dimension(width,height);
        component.setMaximumSize(size);
    }
    static void setMaximumHeightScaledByFont(JComponent component, float scale)
    {
        SwingExtensions.setMaximumSize(
                component,
                component.getMaximumSize().width,
                (int)(component.getFont().getSize()*scale));
    }
}

class QuotaView extends JPanel
{
    // Header
    StatusBar statusbar = new StatusBar("Status Uninitialised");
    JLabel title = new JLabel("Manage Quota/COB");
    JButton refreshButton = new JButton("Refresh");

    JLabel QuotaLabel   = new JLabel("R--.--");
    JLabel COBLabel     = new JLabel("R--.--");
    JLabel BalanceLabel = new JLabel("R--.--");

    JTextArea warningLabel = new JTextArea("""
            WARNING:
            The following inputs are not safe to use yet.
            The CLI version is capable of them and has been tested to work with arbitrary values.
            During testing of the following, the university basically blocked me from increasing, decreasing or using COB.
            It is still not understood why it happened as it operates the same as the CLI, it may just be because of excessive testing.

            It probably works fine for users.
            I had to email the universtiy to clear it up.

            I apologize for the inconvenience.
            Use at your own risk.
            """);


    BalanceRequestInput QuotaIncreaseInput = new BalanceRequestInput("Increase Quota");
    BalanceRequestInput QuotaDecreaseInput = new BalanceRequestInput("Decrease Quota");
    BalanceRequestInput COBIncreaseInput   = new BalanceRequestInput("Increase COB");
    BalanceRequestInput COBDecreaseInput   = new BalanceRequestInput("Decrease COB");

    class InformationRow extends JPanel
    {
        InformationRow(String description, JLabel value)
        {
            setLayout(new GridLayout(1, 2));
            var descriptionLabel = new JLabel(description);

            InformationRow.styleLabel(descriptionLabel);
            InformationRow.styleLabel(value);
            SwingExtensions.setMaximumHeightScaledByFont(this, 3);

            add(descriptionLabel);
            add(value);
        }

        public static void styleLabel(JLabel label) {
            if (label == null) return;

            label.setOpaque(true);
            label.setBackground(Color.WHITE);

            Border topBottomBorder = BorderFactory.createMatteBorder(
                    1, 1, 1, 1, Color.LIGHT_GRAY
                    );

            label.setBorder(topBottomBorder);
        }
    }

    class BalanceRequestInput extends LabelNumberSpinner
    {
        BalanceRequestInput(String description)
        {
            super(description, "Request", 0, Double.MAX_VALUE, 0.01);
            SwingExtensions.setMaximumSize(this, Integer.MAX_VALUE, 50);
        }
    }

    QuotaView()
    {
        // NOTE: most of this generated by ChatGPT, so I dont really know whats
        // happening here
        setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        setBorder(BorderFactory.createEmptyBorder(15, 20, 15, 20));

        // Top heading
        JPanel heading = new JPanel(new BorderLayout());
        JLabel title = new JLabel("Manage Quota/COB");

        // TODO: I dont like hardcoding UI sizes like this
        var headingPreferredSize = new Dimension(Integer.MAX_VALUE, 50);
        heading.setMaximumSize(headingPreferredSize);
        heading.add(statusbar, BorderLayout.NORTH);
        heading.add(title, BorderLayout.CENTER);
        heading.add(refreshButton, BorderLayout.EAST);
        add(heading);

        add(new InformationRow("Your current quota", QuotaLabel));
        add(new InformationRow("Your current COB quota", COBLabel));
        add(new InformationRow("Your available balance", BalanceLabel));
        add(Box.createVerticalStrut(20));

        warningLabel.setBackground(Color.yellow);
        JDebug.addDebugFeatures(warningLabel);
        warningLabel.setEditable(false);
        SwingExtensions.setMaximumHeightScaledByFont(warningLabel, 14);
        add(warningLabel);

        add(QuotaIncreaseInput);
        add(QuotaDecreaseInput);
        add(COBIncreaseInput);
        add(COBDecreaseInput);

        statusbar.setStatus("Status Uninitialized", Color.lightGray);
    }

    void onRefreshPressed(ActionListener listener) { refreshButton.addActionListener(listener); }
    void onIncreaseQuotaPressed(ActionListener listener) { QuotaIncreaseInput.addActionListener(listener); }
    void onDecreaseQuotaPressed(ActionListener listener) { QuotaDecreaseInput.addActionListener(listener); }
    void onIncreaseCOBPressed  (ActionListener listener) { COBIncreaseInput  .addActionListener(listener); }
    void onDecreaseCOBPressed  (ActionListener listener) { COBDecreaseInput  .addActionListener(listener); }

    void setQuotaSummary(QuotaSummary qs)
    {
        SwingUtilities.invokeLater(() -> {
            if (qs.quotaPendingMessage != null)
                statusbar.setStatus("Balance not up-to-date: " + qs.quotaPendingMessage, Color.yellow);
            QuotaLabel.setText(qs.currentQuotaDesc);
            COBLabel.setText(qs.cobQuotaDesc);
            BalanceLabel.setText(qs.balanceDesc);
        });
    }

}

// TODO: I dont like this pattern
// using it Calendar as well
// TODO: COB and Quota seperation becoming cumbersome
class QuotaController
{
    QuotaView view = new QuotaView();
    QuotaController(MainController MControl)
    {
        view.onRefreshPressed(e -> {
            view.statusbar.setStatus("Refreshing Quota Summary...", Color.lightGray);
            MControl.refreshQuotaSummary();
        });
        view.onIncreaseQuotaPressed(e -> MControl.increaseQuota(increaseQuotaValue()));
        view.onDecreaseQuotaPressed(e -> MControl.decreaseQuota(decreaseQuotaValue()));
        view.onIncreaseCOBPressed  (e -> MControl.increaseCOB  (increaseCOBValue  ()));
        view.onDecreaseCOBPressed  (e -> MControl.decreaseCOB  (decreaseCOBValue  ()));
    }

    void setQuotaSummary(QuotaSummary qs)
    {
        view.setQuotaSummary(qs);
    }

    float balanceValueHelper(LabelNumberSpinner input)
    { return input.getValueAsFloat(); };
    // TODO: again, cumbersome
    float increaseQuotaValue() { return balanceValueHelper(view.QuotaIncreaseInput); }
    float decreaseQuotaValue() { return balanceValueHelper(view.QuotaDecreaseInput); }
    float increaseCOBValue  () { return balanceValueHelper(view.COBIncreaseInput  ); }
    float decreaseCOBValue  () { return balanceValueHelper(view.COBDecreaseInput  ); }
}
